require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ArtsCraftsController do

  # This should return the minimal set of attributes required to create a valid
  # ArtsCraft. As you add validations to ArtsCraft, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ArtsCraftsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all arts_crafts as @arts_crafts" do
      arts_craft = ArtsCraft.create! valid_attributes
      get :index, {}, valid_session
      assigns(:arts_crafts).should eq([arts_craft])
    end
  end

  describe "GET show" do
    it "assigns the requested arts_craft as @arts_craft" do
      arts_craft = ArtsCraft.create! valid_attributes
      get :show, {:id => arts_craft.to_param}, valid_session
      assigns(:arts_craft).should eq(arts_craft)
    end
  end

  describe "GET new" do
    it "assigns a new arts_craft as @arts_craft" do
      get :new, {}, valid_session
      assigns(:arts_craft).should be_a_new(ArtsCraft)
    end
  end

  describe "GET edit" do
    it "assigns the requested arts_craft as @arts_craft" do
      arts_craft = ArtsCraft.create! valid_attributes
      get :edit, {:id => arts_craft.to_param}, valid_session
      assigns(:arts_craft).should eq(arts_craft)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ArtsCraft" do
        expect {
          post :create, {:arts_craft => valid_attributes}, valid_session
        }.to change(ArtsCraft, :count).by(1)
      end

      it "assigns a newly created arts_craft as @arts_craft" do
        post :create, {:arts_craft => valid_attributes}, valid_session
        assigns(:arts_craft).should be_a(ArtsCraft)
        assigns(:arts_craft).should be_persisted
      end

      it "redirects to the created arts_craft" do
        post :create, {:arts_craft => valid_attributes}, valid_session
        response.should redirect_to(ArtsCraft.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved arts_craft as @arts_craft" do
        # Trigger the behavior that occurs when invalid params are submitted
        ArtsCraft.any_instance.stub(:save).and_return(false)
        post :create, {:arts_craft => { "name" => "invalid value" }}, valid_session
        assigns(:arts_craft).should be_a_new(ArtsCraft)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ArtsCraft.any_instance.stub(:save).and_return(false)
        post :create, {:arts_craft => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested arts_craft" do
        arts_craft = ArtsCraft.create! valid_attributes
        # Assuming there are no other arts_crafts in the database, this
        # specifies that the ArtsCraft created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ArtsCraft.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => arts_craft.to_param, :arts_craft => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested arts_craft as @arts_craft" do
        arts_craft = ArtsCraft.create! valid_attributes
        put :update, {:id => arts_craft.to_param, :arts_craft => valid_attributes}, valid_session
        assigns(:arts_craft).should eq(arts_craft)
      end

      it "redirects to the arts_craft" do
        arts_craft = ArtsCraft.create! valid_attributes
        put :update, {:id => arts_craft.to_param, :arts_craft => valid_attributes}, valid_session
        response.should redirect_to(arts_craft)
      end
    end

    describe "with invalid params" do
      it "assigns the arts_craft as @arts_craft" do
        arts_craft = ArtsCraft.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ArtsCraft.any_instance.stub(:save).and_return(false)
        put :update, {:id => arts_craft.to_param, :arts_craft => { "name" => "invalid value" }}, valid_session
        assigns(:arts_craft).should eq(arts_craft)
      end

      it "re-renders the 'edit' template" do
        arts_craft = ArtsCraft.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ArtsCraft.any_instance.stub(:save).and_return(false)
        put :update, {:id => arts_craft.to_param, :arts_craft => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested arts_craft" do
      arts_craft = ArtsCraft.create! valid_attributes
      expect {
        delete :destroy, {:id => arts_craft.to_param}, valid_session
      }.to change(ArtsCraft, :count).by(-1)
    end

    it "redirects to the arts_crafts list" do
      arts_craft = ArtsCraft.create! valid_attributes
      delete :destroy, {:id => arts_craft.to_param}, valid_session
      response.should redirect_to(arts_crafts_url)
    end
  end

end
